App 899 sales force app json to plaintext parser
symphonyoss/App-Integrations-Salesforce pull request #14
Opened 2017-03-28 16:54 UTC by crepache

Changes in service OpportunityNotification about Salesforce Integration:

- XML integration continues to work.
- New JSON integration parser.
- Unit test about integration JSON.

2017-03-28 20:30 UTC, robson-sanchez requested changes

2017-03-28 20:30 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +  private static final String typeJSON = "application/json";
You don't need to declare this constant, you should use MediaType.APPLICATION_JSON.

2017-03-28 20:30 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +        messageML = processIntegrationWithJSON(input);
You can deal with IOException inside the method. 

Something like that: 

```
if (isContentTypeJSON(input)) {
  return processIntegrationWithJSON(input);
}
```

Inside the 'processIntegrationWithJSON' you should throw the parse exception.

2017-03-28 20:30 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +    return getContentType(payload).equals(typeJSON);
You should simplify this using something like that:

```
return MediaType.APPLICATION_JSON.equals(getContentType(payload));
```

2017-03-28 20:30 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +    return payload.getHeaders().get("content-type").toString();
toString() is not required.

2017-03-28 20:30 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +  }
I think this method is not required.

2017-03-28 20:30 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +    String type = OPPORTUNITY_NOTIFICATION_JSON;
You don't need the variable 'type'

2017-03-29 11:56 UTC, ecarrenho-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +          "Something went wrong when trying to validate the MessageML received to object.", e);
Something went wrong when trying parse the JSON payload received by the webhook.

2017-03-29 11:58 UTC, ecarrenho-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> +      return presentationFormat(LINKED_FORMATTED, presentationFormat(MessageMLFormatConstants.MESSAGEML_MENTION_EMAIL_FORMAT, ownerEmail));
Why is it necessary to invoke presentationFormat twice here?

2017-03-29 11:59 UTC, ecarrenho-daitan commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/OpportunityNotificationJSONParserTest.java
> +  public void LINKED_FORMATTED() throws JAXBException, IOException {
Use camel case on function names.

2017-03-29 12:04 UTC, ecarrenho-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> +    format = format.clear().append(safeString.toString()).append("<br/>%s");
getting the string from a SafeString will cause double escaping issues.

2017-03-29 12:21 UTC, ecarrenho-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> +    return presentationFormat("Next Step: %s", nextStep);
Add constants to these strings.

2017-03-29 12:23 UTC, ecarrenho-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> +  protected SafeString getProbabilityFormatted(JsonNode node) {
Make a common method the encapsulates the logic for checking empty, and pass the JSON node and formatting string to it.

2017-03-29 12:27 UTC, robson-sanchez approved these changes

2017-03-30 21:17 UTC, ecarrenho-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +      return processIntegrationWithJSON(input);
Change function name: parseJsonPayload

2017-03-31 00:15 UTC, ecarrenho-daitan commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> +    return node.path("Owner").path("Name").asText();
Add all these string constants to SalesforceConstants class.

2017-03-31 16:26 UTC, ecarrenho-daitan commented
@crepache There is missing field to be displayed - opportunity name.

2017-03-31 23:37 UTC, dnsymphony requested changes

2017-03-31 23:37 UTC, dnsymphony commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +    String messageML;
Why did you move this declaration?  In general, it is best to keep scope of variables as narrow as possible.  Previously, it was declared when at the time it is first used.  Putting variable declaration at the top of the method is very 'C'/'C++' like.

2017-03-31 23:37 UTC, dnsymphony commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/AccountStatusParser.java
> +    return null;
null? Is this right?

2017-03-31 23:37 UTC, dnsymphony commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> -  /**
Why did you delete the comments?

2017-03-31 23:37 UTC, dnsymphony commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/OpportunityNotificationParser.java
> +    return null;
null?

2017-04-03 13:00 UTC, crepache commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/OpportunityNotificationParser.java
> +    return null;
Adding exception instead of returning null.

2017-04-03 13:01 UTC, crepache commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> -  /**
Returning removed comments.

2017-04-03 13:01 UTC, crepache commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/AccountStatusParser.java
> +    return null;
Adding exception instead of returning null.

2017-04-03 13:01 UTC, crepache commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegration.java
> +    String messageML;
Done.

2017-04-03 19:57 UTC, dnsymphony approved these changes

2017-04-05 16:20 UTC, dnsymphony commented on src/main/java/org/symphonyoss/integration/webhook/salesforce/parser/BaseSalesforceParser.java
> +  protected SafeString getFieldsUpdated(JsonNode node) {
Is there a unit test class for this class?  I see new methods here, but no new unit tests.

2017-04-13 22:02 UTC, merged