App 959 update readme salesforce
symphonyoss/App-Integrations-Salesforce pull request #23
Opened 2017-05-05 17:09 UTC by crepache

Update README with MessageML v1 and v2.

2017-05-05 18:37 UTC, robson-sanchez requested changes
Small changes

2017-05-05 18:37 UTC, rsanchez-daitan commented on README.md
>  ### Opportunity Notification
You might identify that this event has two different formats.

Something like that: "The opportunity notification may have two different formats: XML or JSON"

2017-05-05 18:37 UTC, rsanchez-daitan commented on README.md
> +* Payload with content-type XML sent from Salesforce
* XML Payload

2017-05-05 18:37 UTC, rsanchez-daitan commented on README.md
> +* Payload with content-type JSON sent from Salesforce
* JSON Payload

2017-05-08 19:32 UTC, crepache commented on README.md
> +* Payload with content-type XML sent from Salesforce
Done.

2017-05-08 19:32 UTC, crepache commented on README.md
> +* Payload with content-type JSON sent from Salesforce
Done.

2017-05-08 19:33 UTC, crepache commented on README.md
>  ### Opportunity Notification
Done.

2017-05-10 11:23 UTC, robson-sanchez approved these changes

2017-05-10 11:24 UTC, merged