Increasing the coverage tests for 90%
symphonyoss/App-Integrations-Salesforce pull request #43
Opened 2017-06-13 18:47 UTC by crepache

Increasing the coverage tests for 90%

2017-06-14 17:47 UTC, luanapp requested changes

2017-06-14 17:47 UTC, luanapp commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegrationTest.java
> +  private V1ParserFactory v1ParserFactory;
I think this class methods (parse) can be tested in its test class V1ParserFactoryTest. 
Thus, as this class works as a proxy for some classes (SalesforceParserFactory and SalesforceParserResolver), you can use the verify to check if those class methods are being called

2017-06-14 17:47 UTC, luanapp commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegrationTest.java
> +    Assert.assertEquals(salesforceWebHookIntegration.getSupportedContentTypes(), supportedContentTypes);
The expected result is the first parameter

2017-06-14 17:47 UTC, luanapp commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/SalesforceParserResolverTest.java
> +  private V1ParserFactory v1ParserFactory;
This field doen't need to be a @Spy since nothing in this class is being called, just the reference being compared

2017-06-14 17:47 UTC, luanapp commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/SalesforceParserResolverTest.java
> +  private V2ParserFactory v2ParserFactory;
This field doen't need to be a @Spy since nothing in this class is being called, just the reference being compared

2017-06-14 17:47 UTC, aurojr commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/AccountStatusParserTest.java
> +import com.fasterxml.jackson.databind.JsonNode;
Remove unused imports

2017-06-14 17:47 UTC, aurojr commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/OpportunityNotificationParserTest.java
> +import com.fasterxml.jackson.databind.JsonNode;
Remove unused imports

2017-06-14 17:47 UTC, aurojr commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v2/OpportunityNotificationMetadataParserTest.java
> +import com.fasterxml.jackson.databind.node.JsonNodeFactory;
Remove unused imports

2017-06-14 17:59 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v2/OpportunityNotificationMetadataParserTest.java
> +import com.fasterxml.jackson.databind.node.JsonNodeFactory;
Done.

2017-06-14 17:59 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/OpportunityNotificationParserTest.java
> +import com.fasterxml.jackson.databind.JsonNode;
Done.

2017-06-14 18:00 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/AccountStatusParserTest.java
> +import com.fasterxml.jackson.databind.JsonNode;
Done.

2017-06-14 18:02 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/SalesforceParserResolverTest.java
> +  private V2ParserFactory v2ParserFactory;
Done.

2017-06-14 18:02 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/SalesforceParserResolverTest.java
> +  private V1ParserFactory v1ParserFactory;
Done.

2017-06-15 11:53 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegrationTest.java
> +    Assert.assertEquals(salesforceWebHookIntegration.getSupportedContentTypes(), supportedContentTypes);
Done.

2017-06-15 11:53 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/SalesforceWebHookIntegrationTest.java
> +  private V1ParserFactory v1ParserFactory;
Done.

2017-06-15 14:10 UTC, robson-sanchez requested changes

2017-06-15 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/NullSalesforceParserTest.java
> +    salesforceParser.parse(null, JsonNodeFactory.instance.objectNode());
Include assert.

2017-06-15 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    //beans.add(defaultSalesforceParser);
Remove the comments.

2017-06-15 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    factory.getParser(payload).getEvents();
You might change to: factory.getParser(payload)

2017-06-15 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    Assert.assertEquals(0, factory.getParser(payload).getEvents().size());
You should change 'factory.getParser(payload).getEvents().size()' to 'webHookParser.getEvents().size()'

2017-06-15 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    String xml = readFile("executiveReport.xml");
This event is the same of the previous test.

2017-06-15 14:10 UTC, rsanchez-daitan commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v2/V2SalesforceParserFactoryTest.java
> +    factory.getParser(payload).getEvents();
Change to factory.getParser(payload)

2017-06-15 14:12 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    factory.getParser(payload).getEvents();
Done.

2017-06-15 14:12 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    //beans.add(defaultSalesforceParser);
Done.

2017-06-15 14:14 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/NullSalesforceParserTest.java
> +    salesforceParser.parse(null, JsonNodeFactory.instance.objectNode());
Done.

2017-06-15 14:15 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    Assert.assertEquals(0, factory.getParser(payload).getEvents().size());
Done.

2017-06-15 14:17 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v2/V2SalesforceParserFactoryTest.java
> +    factory.getParser(payload).getEvents();
Done.

2017-06-15 14:17 UTC, crepache commented on src/test/java/org/symphonyoss/integration/webhook/salesforce/parser/v1/V1SalesforceParserFactoryTest.java
> +    String xml = readFile("executiveReport.xml");
Done.

2017-06-15 14:20 UTC, robson-sanchez approved these changes

2017-06-15 14:21 UTC, merged